// Mock venue data for Toronto — simulates Google Places API responses
// Each venue has a fake place_id that maps to what Google would return

export interface VenueResult {
  place_id: string;
  name: string;
  venue_type: "Club" | "Bar" | "Warehouse" | "Gallery" | "Rooftop";
  neighbourhood: string;
  address: string;
  city: string;
  rating: number;
  review_count: number;
  phone: string;
  website: string;
  capacity: number | null;
  latitude: number;
  longitude: number;
  photo_url: string | null;
  hours: { day: string; open: string; close: string }[] | null;
}

export const MOCK_VENUES: VenueResult[] = [
  {
    place_id: "ChIJcoda_toronto_001",
    name: "CODA",
    venue_type: "Club",
    neighbourhood: "Queen West",
    address: "794 Bathurst St, Toronto, ON M5S 2R6",
    city: "Toronto",
    rating: 4.5,
    review_count: 1200,
    phone: "(416) 536-2632",
    website: "https://codatoronto.com",
    capacity: 400,
    latitude: 43.6634,
    longitude: -79.4115,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:00 PM", close: "5:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "5:00 AM" },
      { day: "Sunday", open: "10:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJvelvet_toronto_002",
    name: "Velvet Underground",
    venue_type: "Club",
    neighbourhood: "Queen West",
    address: "508 Queen St W, Toronto, ON M5V 2B3",
    city: "Toronto",
    rating: 4.3,
    review_count: 890,
    phone: "(416) 504-6688",
    website: "https://thevelvet.ca",
    capacity: 350,
    latitude: 43.649,
    longitude: -79.4009,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "9:00 PM", close: "3:00 AM" },
      { day: "Friday", open: "9:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "9:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJdrake_toronto_003",
    name: "The Drake Underground",
    venue_type: "Bar",
    neighbourhood: "West Queen West",
    address: "1150 Queen St W, Toronto, ON M6J 1J3",
    city: "Toronto",
    rating: 4.4,
    review_count: 2100,
    phone: "(416) 531-5042",
    website: "https://thedrake.ca",
    capacity: 250,
    latitude: 43.6427,
    longitude: -79.4269,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "8:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "8:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJtoybox_toronto_004",
    name: "Toybox",
    venue_type: "Club",
    neighbourhood: "Richmond Row",
    address: "473 Adelaide St W, Toronto, ON M5V 1T1",
    city: "Toronto",
    rating: 4.2,
    review_count: 650,
    phone: "(416) 601-3655",
    website: "https://toyboxto.com",
    capacity: 500,
    latitude: 43.6469,
    longitude: -79.397,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJnest_toronto_005",
    name: "Nest Toronto",
    venue_type: "Rooftop",
    neighbourhood: "Entertainment District",
    address: "423 Adelaide St W, Toronto, ON M5V 1S9",
    city: "Toronto",
    rating: 4.1,
    review_count: 430,
    phone: "(647) 350-6378",
    website: "https://nesttoronto.com",
    capacity: 200,
    latitude: 43.6472,
    longitude: -79.3955,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "5:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Sunday", open: "3:00 PM", close: "11:00 PM" },
    ],
  },
  {
    place_id: "ChIJstackt_toronto_006",
    name: "Stackt Market",
    venue_type: "Warehouse",
    neighbourhood: "Bathurst & Front",
    address: "28 Bathurst St, Toronto, ON M5V 2P1",
    city: "Toronto",
    rating: 4.6,
    review_count: 3200,
    phone: "(416) 803-2153",
    website: "https://stacktmarket.com",
    capacity: 800,
    latitude: 43.64,
    longitude: -79.4017,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "12:00 PM", close: "10:00 PM" },
      { day: "Thursday", open: "12:00 PM", close: "10:00 PM" },
      { day: "Friday", open: "12:00 PM", close: "12:00 AM" },
      { day: "Saturday", open: "10:00 AM", close: "12:00 AM" },
      { day: "Sunday", open: "10:00 AM", close: "8:00 PM" },
    ],
  },
  {
    place_id: "ChIJgreathall_toronto_007",
    name: "The Great Hall",
    venue_type: "Gallery",
    neighbourhood: "Queen West",
    address: "1087 Queen St W, Toronto, ON M6J 1H3",
    city: "Toronto",
    rating: 4.7,
    review_count: 1800,
    phone: "(416) 792-1268",
    website: "https://thegreathall.ca",
    capacity: 1000,
    latitude: 43.6431,
    longitude: -79.424,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "7:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "7:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "7:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJrebel_toronto_008",
    name: "Rebel",
    venue_type: "Club",
    neighbourhood: "Port Lands",
    address: "11 Polson St, Toronto, ON M5A 1A4",
    city: "Toronto",
    rating: 4.0,
    review_count: 5600,
    phone: "(416) 461-7867",
    website: "https://rebeltoronto.com",
    capacity: 3000,
    latitude: 43.638,
    longitude: -79.3535,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJbambis_toronto_009",
    name: "Bambi's",
    venue_type: "Bar",
    neighbourhood: "Dundas West",
    address: "1265 Dundas St W, Toronto, ON M6J 1X6",
    city: "Toronto",
    rating: 4.4,
    review_count: 720,
    phone: "(416) 560-5757",
    website: "https://bambistoronto.com",
    capacity: 150,
    latitude: 43.6507,
    longitude: -79.4254,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "6:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "6:00 PM", close: "3:00 AM" },
      { day: "Sunday", open: "6:00 PM", close: "12:00 AM" },
    ],
  },
  {
    place_id: "ChIJevergreen_toronto_010",
    name: "Evergreen Brick Works",
    venue_type: "Gallery",
    neighbourhood: "Don Valley",
    address: "550 Bayview Ave, Toronto, ON M4W 3X8",
    city: "Toronto",
    rating: 4.6,
    review_count: 4100,
    phone: "(416) 596-7670",
    website: "https://evergreen.ca/evergreen-brick-works",
    capacity: 1500,
    latitude: 43.6847,
    longitude: -79.3648,
    photo_url: null,
    hours: [
      { day: "Monday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Tuesday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Wednesday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Thursday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Friday", open: "9:00 AM", close: "9:00 PM" },
      { day: "Saturday", open: "8:00 AM", close: "5:00 PM" },
      { day: "Sunday", open: "10:00 AM", close: "5:00 PM" },
    ],
  },
  {
    place_id: "ChIJlula_toronto_011",
    name: "Lula Lounge",
    venue_type: "Bar",
    neighbourhood: "Dundas West",
    address: "1585 Dundas St W, Toronto, ON M6K 1T9",
    city: "Toronto",
    rating: 4.5,
    review_count: 950,
    phone: "(416) 588-0307",
    website: "https://lula.ca",
    capacity: 300,
    latitude: 43.6499,
    longitude: -79.4344,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "7:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "8:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "8:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJhistory_toronto_012",
    name: "History",
    venue_type: "Club",
    neighbourhood: "Liberty Village",
    address: "1663 Queen St E, Toronto, ON M4L 1G5",
    city: "Toronto",
    rating: 4.3,
    review_count: 2400,
    phone: "(416) 368-0575",
    website: "https://historytoronto.com",
    capacity: 2500,
    latitude: 43.6617,
    longitude: -79.329,
    photo_url: null,
    hours: [
      { day: "Friday", open: "9:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "9:00 PM", close: "4:00 AM" },
    ],
  },
];
