// Mock venue data for Toronto — simulates Google Places API responses
// Each venue has a fake place_id that maps to what Google would return

export interface VenueResult {
  place_id: string;
  name: string;
  venue_type: "Club" | "Bar" | "Warehouse" | "Gallery" | "Rooftop" | "Live Music" | "Underground";
  neighbourhood: string;
  address: string;
  city: string;
  rating: number;
  review_count: number;
  phone: string;
  website: string;
  capacity: number | null;
  latitude: number;
  longitude: number;
  photo_url: string | null;
  hours: { day: string; open: string; close: string }[] | null;
}

export const MOCK_VENUES: VenueResult[] = [
  {
    place_id: "ChIJcoda_toronto_001",
    name: "CODA",
    venue_type: "Club",
    neighbourhood: "Queen West",
    address: "794 Bathurst St, Toronto, ON M5S 2R6",
    city: "Toronto",
    rating: 4.5,
    review_count: 1200,
    phone: "(416) 536-2632",
    website: "https://codatoronto.com",
    capacity: 400,
    latitude: 43.6634,
    longitude: -79.4115,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:00 PM", close: "5:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "5:00 AM" },
      { day: "Sunday", open: "10:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJvelvet_toronto_002",
    name: "Velvet Underground",
    venue_type: "Club",
    neighbourhood: "Queen West",
    address: "508 Queen St W, Toronto, ON M5V 2B3",
    city: "Toronto",
    rating: 4.3,
    review_count: 890,
    phone: "(416) 504-6688",
    website: "https://thevelvet.ca",
    capacity: 350,
    latitude: 43.649,
    longitude: -79.4009,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "9:00 PM", close: "3:00 AM" },
      { day: "Friday", open: "9:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "9:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJdrake_toronto_003",
    name: "The Drake Underground",
    venue_type: "Bar",
    neighbourhood: "West Queen West",
    address: "1150 Queen St W, Toronto, ON M6J 1J3",
    city: "Toronto",
    rating: 4.4,
    review_count: 2100,
    phone: "(416) 531-5042",
    website: "https://thedrake.ca",
    capacity: 250,
    latitude: 43.6427,
    longitude: -79.4269,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "8:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "8:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJtoybox_toronto_004",
    name: "Toybox",
    venue_type: "Club",
    neighbourhood: "Richmond Row",
    address: "473 Adelaide St W, Toronto, ON M5V 1T1",
    city: "Toronto",
    rating: 4.2,
    review_count: 650,
    phone: "(416) 601-3655",
    website: "https://toyboxto.com",
    capacity: 500,
    latitude: 43.6469,
    longitude: -79.397,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJnest_toronto_005",
    name: "Nest Toronto",
    venue_type: "Rooftop",
    neighbourhood: "Entertainment District",
    address: "423 Adelaide St W, Toronto, ON M5V 1S9",
    city: "Toronto",
    rating: 4.1,
    review_count: 430,
    phone: "(647) 350-6378",
    website: "https://nesttoronto.com",
    capacity: 200,
    latitude: 43.6472,
    longitude: -79.3955,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "5:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Sunday", open: "3:00 PM", close: "11:00 PM" },
    ],
  },
  {
    place_id: "ChIJstackt_toronto_006",
    name: "Stackt Market",
    venue_type: "Warehouse",
    neighbourhood: "Bathurst & Front",
    address: "28 Bathurst St, Toronto, ON M5V 2P1",
    city: "Toronto",
    rating: 4.6,
    review_count: 3200,
    phone: "(416) 803-2153",
    website: "https://stacktmarket.com",
    capacity: 800,
    latitude: 43.64,
    longitude: -79.4017,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "12:00 PM", close: "10:00 PM" },
      { day: "Thursday", open: "12:00 PM", close: "10:00 PM" },
      { day: "Friday", open: "12:00 PM", close: "12:00 AM" },
      { day: "Saturday", open: "10:00 AM", close: "12:00 AM" },
      { day: "Sunday", open: "10:00 AM", close: "8:00 PM" },
    ],
  },
  {
    place_id: "ChIJgreathall_toronto_007",
    name: "The Great Hall",
    venue_type: "Gallery",
    neighbourhood: "Queen West",
    address: "1087 Queen St W, Toronto, ON M6J 1H3",
    city: "Toronto",
    rating: 4.7,
    review_count: 1800,
    phone: "(416) 792-1268",
    website: "https://thegreathall.ca",
    capacity: 1000,
    latitude: 43.6431,
    longitude: -79.424,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "7:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "7:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "7:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJrebel_toronto_008",
    name: "Rebel",
    venue_type: "Club",
    neighbourhood: "Port Lands",
    address: "11 Polson St, Toronto, ON M5A 1A4",
    city: "Toronto",
    rating: 4.0,
    review_count: 5600,
    phone: "(416) 461-7867",
    website: "https://rebeltoronto.com",
    capacity: 3000,
    latitude: 43.638,
    longitude: -79.3535,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJbambis_toronto_009",
    name: "Bambi's",
    venue_type: "Bar",
    neighbourhood: "Dundas West",
    address: "1265 Dundas St W, Toronto, ON M6J 1X6",
    city: "Toronto",
    rating: 4.4,
    review_count: 720,
    phone: "(416) 560-5757",
    website: "https://bambistoronto.com",
    capacity: 150,
    latitude: 43.6507,
    longitude: -79.4254,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "6:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "6:00 PM", close: "3:00 AM" },
      { day: "Sunday", open: "6:00 PM", close: "12:00 AM" },
    ],
  },
  {
    place_id: "ChIJevergreen_toronto_010",
    name: "Evergreen Brick Works",
    venue_type: "Gallery",
    neighbourhood: "Don Valley",
    address: "550 Bayview Ave, Toronto, ON M4W 3X8",
    city: "Toronto",
    rating: 4.6,
    review_count: 4100,
    phone: "(416) 596-7670",
    website: "https://evergreen.ca/evergreen-brick-works",
    capacity: 1500,
    latitude: 43.6847,
    longitude: -79.3648,
    photo_url: null,
    hours: [
      { day: "Monday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Tuesday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Wednesday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Thursday", open: "9:00 AM", close: "5:00 PM" },
      { day: "Friday", open: "9:00 AM", close: "9:00 PM" },
      { day: "Saturday", open: "8:00 AM", close: "5:00 PM" },
      { day: "Sunday", open: "10:00 AM", close: "5:00 PM" },
    ],
  },
  {
    place_id: "ChIJlula_toronto_011",
    name: "Lula Lounge",
    venue_type: "Bar",
    neighbourhood: "Dundas West",
    address: "1585 Dundas St W, Toronto, ON M6K 1T9",
    city: "Toronto",
    rating: 4.5,
    review_count: 950,
    phone: "(416) 588-0307",
    website: "https://lula.ca",
    capacity: 300,
    latitude: 43.6499,
    longitude: -79.4344,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "7:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "8:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "8:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJhistory_toronto_012",
    name: "History",
    venue_type: "Club",
    neighbourhood: "Liberty Village",
    address: "1663 Queen St E, Toronto, ON M4L 1G5",
    city: "Toronto",
    rating: 4.3,
    review_count: 2400,
    phone: "(416) 368-0575",
    website: "https://historytoronto.com",
    capacity: 2500,
    latitude: 43.6617,
    longitude: -79.329,
    photo_url: null,
    hours: [
      { day: "Friday", open: "9:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "9:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJbisha_toronto_013",
    name: "Bisha Hotel Nightclub",
    venue_type: "Club",
    neighbourhood: "Entertainment District",
    address: "80 Blue Jays Way, Toronto, ON M5V 2G3",
    city: "Toronto",
    rating: 4.1,
    review_count: 1850,
    phone: "(416) 999-8801",
    website: "https://bishahoteltoronto.com",
    capacity: 600,
    latitude: 43.6426,
    longitude: -79.3892,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJefs_toronto_014",
    name: "EFS",
    venue_type: "Club",
    neighbourhood: "Entertainment District",
    address: "647 King St W, Toronto, ON M5V 1M5",
    city: "Toronto",
    rating: 4.0,
    review_count: 980,
    phone: "(416) 849-1090",
    website: "https://efstoronto.com",
    capacity: 450,
    latitude: 43.6444,
    longitude: -79.4015,
    photo_url: null,
    hours: [
      { day: "Friday", open: "10:30 PM", close: "4:00 AM" },
      { day: "Saturday", open: "10:30 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJlavelle_toronto_015",
    name: "Lavelle",
    venue_type: "Rooftop",
    neighbourhood: "King West",
    address: "627 King St W, Toronto, ON M5V 1M5",
    city: "Toronto",
    rating: 4.2,
    review_count: 2200,
    phone: "(416) 852-7152",
    website: "https://lavelle.com",
    capacity: 350,
    latitude: 43.6445,
    longitude: -79.4008,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "5:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Sunday", open: "12:00 PM", close: "10:00 PM" },
    ],
  },
  {
    place_id: "ChIJbarraval_toronto_016",
    name: "Bar Raval",
    venue_type: "Bar",
    neighbourhood: "Little Italy",
    address: "505 College St, Toronto, ON M6G 1A5",
    city: "Toronto",
    rating: 4.6,
    review_count: 1400,
    phone: "(647) 344-8001",
    website: "https://thisisbarraval.com",
    capacity: 80,
    latitude: 43.6563,
    longitude: -79.4126,
    photo_url: null,
    hours: [
      { day: "Monday", open: "8:00 AM", close: "12:00 AM" },
      { day: "Tuesday", open: "8:00 AM", close: "12:00 AM" },
      { day: "Wednesday", open: "8:00 AM", close: "12:00 AM" },
      { day: "Thursday", open: "8:00 AM", close: "1:00 AM" },
      { day: "Friday", open: "8:00 AM", close: "2:00 AM" },
      { day: "Saturday", open: "9:00 AM", close: "2:00 AM" },
      { day: "Sunday", open: "9:00 AM", close: "11:00 PM" },
    ],
  },
  {
    place_id: "ChIJcivillib_toronto_017",
    name: "Civil Liberties",
    venue_type: "Bar",
    neighbourhood: "Kensington Market",
    address: "878 Bloor St W, Toronto, ON M6G 1M4",
    city: "Toronto",
    rating: 4.7,
    review_count: 620,
    phone: "(416) 920-0228",
    website: "https://civilliberties.ca",
    capacity: 45,
    latitude: 43.6609,
    longitude: -79.4246,
    photo_url: null,
    hours: [
      { day: "Tuesday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Wednesday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Saturday", open: "6:00 PM", close: "2:00 AM" },
    ],
  },
  {
    place_id: "ChIJbarchef_toronto_018",
    name: "BarChef",
    venue_type: "Bar",
    neighbourhood: "Queen West",
    address: "472 Queen St W, Toronto, ON M5V 2B2",
    city: "Toronto",
    rating: 4.5,
    review_count: 1100,
    phone: "(416) 868-4800",
    website: "https://bfresto.com",
    capacity: 100,
    latitude: 43.6492,
    longitude: -79.3983,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Saturday", open: "6:00 PM", close: "2:00 AM" },
    ],
  },
  {
    place_id: "ChIJcocktailbar_toronto_019",
    name: "Cocktail Bar",
    venue_type: "Bar",
    neighbourhood: "Dundas West",
    address: "923 Dundas St W, Toronto, ON M6J 1W3",
    city: "Toronto",
    rating: 4.4,
    review_count: 780,
    phone: "(416) 792-7511",
    website: "https://cocktailbarto.com",
    capacity: 120,
    latitude: 43.6515,
    longitude: -79.4153,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "6:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "6:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "6:00 PM", close: "3:00 AM" },
      { day: "Sunday", open: "6:00 PM", close: "12:00 AM" },
    ],
  },
  {
    place_id: "ChIJ99sudbury_toronto_020",
    name: "99 Sudbury",
    venue_type: "Warehouse",
    neighbourhood: "West Queen West",
    address: "99 Sudbury St, Toronto, ON M6J 3S7",
    city: "Toronto",
    rating: 4.3,
    review_count: 560,
    phone: "(416) 603-0099",
    website: "https://99sudbury.com",
    capacity: 700,
    latitude: 43.6408,
    longitude: -79.4183,
    photo_url: null,
    hours: [
      { day: "Friday", open: "8:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "8:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJwarehouse_toronto_021",
    name: "The Warehouse",
    venue_type: "Warehouse",
    neighbourhood: "Liberty Village",
    address: "6 Noble St, Toronto, ON M6K 2C9",
    city: "Toronto",
    rating: 4.1,
    review_count: 340,
    phone: "(416) osc-0000",
    website: "https://thewarehousetoronto.com",
    capacity: 500,
    latitude: 43.6388,
    longitude: -79.4219,
    photo_url: null,
    hours: [
      { day: "Friday", open: "9:00 PM", close: "4:00 AM" },
      { day: "Saturday", open: "9:00 PM", close: "4:00 AM" },
    ],
  },
  {
    place_id: "ChIJkost_toronto_022",
    name: "Kost",
    venue_type: "Rooftop",
    neighbourhood: "Entertainment District",
    address: "1 Blue Jays Way, 44th Floor, Toronto, ON M5V 1J4",
    city: "Toronto",
    rating: 4.3,
    review_count: 3100,
    phone: "(416) 350-5678",
    website: "https://kosttoronto.com",
    capacity: 250,
    latitude: 43.6418,
    longitude: -79.3893,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "4:00 PM", close: "12:00 AM" },
      { day: "Thursday", open: "4:00 PM", close: "12:00 AM" },
      { day: "Friday", open: "4:00 PM", close: "2:00 AM" },
      { day: "Saturday", open: "11:00 AM", close: "2:00 AM" },
      { day: "Sunday", open: "11:00 AM", close: "10:00 PM" },
    ],
  },
  {
    place_id: "ChIJharriets_toronto_023",
    name: "Harriet's Rooftop",
    venue_type: "Rooftop",
    neighbourhood: "Entertainment District",
    address: "111 Princess St, Toronto, ON M5A 4S1",
    city: "Toronto",
    rating: 4.4,
    review_count: 1600,
    phone: "(416) 595-1111",
    website: "https://harrietsrooftop.com",
    capacity: 180,
    latitude: 43.6504,
    longitude: -79.3613,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "5:00 PM", close: "1:00 AM" },
      { day: "Friday", open: "5:00 PM", close: "2:00 AM" },
      { day: "Saturday", open: "12:00 PM", close: "2:00 AM" },
      { day: "Sunday", open: "12:00 PM", close: "10:00 PM" },
    ],
  },
  {
    place_id: "ChIJhorseshoe_toronto_024",
    name: "The Horseshoe Tavern",
    venue_type: "Live Music",
    neighbourhood: "Queen West",
    address: "370 Queen St W, Toronto, ON M5V 2A2",
    city: "Toronto",
    rating: 4.5,
    review_count: 2800,
    phone: "(416) 598-4226",
    website: "https://horseshoetavern.com",
    capacity: 450,
    latitude: 43.6498,
    longitude: -79.3942,
    photo_url: null,
    hours: [
      { day: "Monday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Tuesday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Wednesday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "8:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "8:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "8:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJleespalace_toronto_025",
    name: "Lee's Palace",
    venue_type: "Live Music",
    neighbourhood: "The Annex",
    address: "529 Bloor St W, Toronto, ON M5S 1Y5",
    city: "Toronto",
    rating: 4.4,
    review_count: 2100,
    phone: "(416) 532-1598",
    website: "https://leespalace.com",
    capacity: 550,
    latitude: 43.6651,
    longitude: -79.4103,
    photo_url: null,
    hours: [
      { day: "Wednesday", open: "8:00 PM", close: "2:30 AM" },
      { day: "Thursday", open: "8:00 PM", close: "2:30 AM" },
      { day: "Friday", open: "8:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "8:00 PM", close: "3:00 AM" },
    ],
  },
  {
    place_id: "ChIJrex_toronto_026",
    name: "The Rex Hotel Jazz & Blues Bar",
    venue_type: "Live Music",
    neighbourhood: "Queen West",
    address: "194 Queen St W, Toronto, ON M5V 1Z1",
    city: "Toronto",
    rating: 4.6,
    review_count: 1700,
    phone: "(416) 598-2475",
    website: "https://therex.ca",
    capacity: 200,
    latitude: 43.6507,
    longitude: -79.3882,
    photo_url: null,
    hours: [
      { day: "Monday", open: "12:00 PM", close: "1:00 AM" },
      { day: "Tuesday", open: "12:00 PM", close: "1:00 AM" },
      { day: "Wednesday", open: "12:00 PM", close: "1:00 AM" },
      { day: "Thursday", open: "12:00 PM", close: "1:00 AM" },
      { day: "Friday", open: "12:00 PM", close: "2:30 AM" },
      { day: "Saturday", open: "12:00 PM", close: "2:30 AM" },
      { day: "Sunday", open: "12:00 PM", close: "12:00 AM" },
    ],
  },
  {
    place_id: "ChIJcameron_toronto_027",
    name: "The Cameron House",
    venue_type: "Live Music",
    neighbourhood: "Queen West",
    address: "408 Queen St W, Toronto, ON M5V 2A7",
    city: "Toronto",
    rating: 4.5,
    review_count: 1300,
    phone: "(416) 703-0811",
    website: "https://thecameron.com",
    capacity: 175,
    latitude: 43.6495,
    longitude: -79.3955,
    photo_url: null,
    hours: [
      { day: "Tuesday", open: "5:00 PM", close: "2:00 AM" },
      { day: "Wednesday", open: "5:00 PM", close: "2:00 AM" },
      { day: "Thursday", open: "5:00 PM", close: "2:00 AM" },
      { day: "Friday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Saturday", open: "5:00 PM", close: "3:00 AM" },
      { day: "Sunday", open: "5:00 PM", close: "12:00 AM" },
    ],
  },
  {
    place_id: "ChIJdanforth_toronto_028",
    name: "The Danforth Music Hall",
    venue_type: "Live Music",
    neighbourhood: "The Danforth",
    address: "147 Danforth Ave, Toronto, ON M4K 1N2",
    city: "Toronto",
    rating: 4.6,
    review_count: 4500,
    phone: "(416) 778-8163",
    website: "https://thedanforth.com",
    capacity: 1500,
    latitude: 43.6776,
    longitude: -79.3525,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "7:00 PM", close: "1:00 AM" },
      { day: "Friday", open: "7:00 PM", close: "2:00 AM" },
      { day: "Saturday", open: "7:00 PM", close: "2:00 AM" },
    ],
  },
  {
    place_id: "ChIJmassey_toronto_029",
    name: "Massey Hall",
    venue_type: "Live Music",
    neighbourhood: "Garden District",
    address: "178 Victoria St, Toronto, ON M5B 1T7",
    city: "Toronto",
    rating: 4.7,
    review_count: 6200,
    phone: "(416) 872-4255",
    website: "https://masseyhall.com",
    capacity: 2765,
    latitude: 43.6542,
    longitude: -79.3781,
    photo_url: null,
    hours: [
      { day: "Monday", open: "12:00 PM", close: "6:00 PM" },
      { day: "Tuesday", open: "12:00 PM", close: "6:00 PM" },
      { day: "Wednesday", open: "12:00 PM", close: "11:00 PM" },
      { day: "Thursday", open: "12:00 PM", close: "11:00 PM" },
      { day: "Friday", open: "12:00 PM", close: "11:00 PM" },
      { day: "Saturday", open: "12:00 PM", close: "11:00 PM" },
    ],
  },
  {
    place_id: "ChIJcomfortzone_toronto_030",
    name: "Comfort Zone",
    venue_type: "Underground",
    neighbourhood: "College & Spadina",
    address: "480 Spadina Ave, Toronto, ON M5T 2G8",
    city: "Toronto",
    rating: 4.2,
    review_count: 890,
    phone: "(416) 975-0909",
    website: "https://comfortzonetoronto.com",
    capacity: 300,
    latitude: 43.6576,
    longitude: -79.3997,
    photo_url: null,
    hours: [
      { day: "Friday", open: "11:00 PM", close: "12:00 PM" },
      { day: "Saturday", open: "11:00 PM", close: "12:00 PM" },
    ],
  },
  {
    place_id: "ChIJvertigo_toronto_031",
    name: "Vertigo",
    venue_type: "Underground",
    neighbourhood: "Richmond Row",
    address: "486 Richmond St W, Toronto, ON M5V 1Y2",
    city: "Toronto",
    rating: 4.0,
    review_count: 420,
    phone: "(416) 504-5667",
    website: "https://vertigotoronto.com",
    capacity: 200,
    latitude: 43.6479,
    longitude: -79.3986,
    photo_url: null,
    hours: [
      { day: "Thursday", open: "10:00 PM", close: "4:00 AM" },
      { day: "Friday", open: "10:00 PM", close: "5:00 AM" },
      { day: "Saturday", open: "10:00 PM", close: "5:00 AM" },
    ],
  },
];
