import { test, expect } from '@playwright/test';

// Minimal smoke test — confirms the app serves a page.
// The full suite is generated by the Day 0 hardening prompt.
test('homepage responds', async ({ page }) => {
  const response = await page.goto('/');
  expect(response?.status()).toBeLessThan(500);
});
