"use server";

import { createAdminClient } from "@/lib/supabase/config";
import { getResendClient } from "@/lib/resend";

// Generate a settlement report email and return it (for now, no Resend — just generates the content)
export async function generateSettlementReport(settlementId: string) {
  const admin = createAdminClient();

  // Get settlement with event and collective
  const { data: settlement } = await admin
    .from("settlements")
    .select("*, events(title, starts_at, venues(name, city)), collectives(name)")
    .eq("id", settlementId)
    .maybeSingle();

  if (!settlement) return { error: "Settlement not found", report: null };

  // Get line items
  const { data: lines } = await admin
    .from("settlement_lines")
    .select("*")
    .eq("settlement_id", settlementId)
    .order("created_at");

  // Get collective members for emailing
  const { data: members } = await admin
    .from("collective_members")
    .select("users(full_name, email)")
    .eq("collective_id", settlement.collective_id)
    .is("deleted_at", null);

  const event = settlement.events as unknown as {
    title: string;
    starts_at: string;
    venues: { name: string; city: string } | null;
  };
  const collective = settlement.collectives as unknown as { name: string };
  const venue = event?.venues;
  const eventDate = new Date(event.starts_at).toLocaleDateString("en", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const recipientEmails = (members ?? [])
    .map((m) => {
      const u = m.users as unknown as { full_name: string; email: string } | null;
      return u?.email;
    })
    .filter(Boolean) as string[];

  // Build report
  const deductions = (lines ?? [])
    .map((l) => `  • ${l.label}: -$${Number(l.amount).toFixed(2)}`)
    .join("\n");

  const subject = `Settlement Report: ${event.title} — ${collective.name}`;

  const body = `Hi ${collective.name} team,

Here's the settlement report for ${event.title}.

EVENT DETAILS
━━━━━━━━━━━━
Event: ${event.title}
Date: ${eventDate}
Venue: ${venue ? `${venue.name}, ${venue.city}` : "N/A"}

FINANCIAL SUMMARY
━━━━━━━━━━━━━━━━
Gross Revenue:    $${Number(settlement.gross_revenue).toFixed(2)}

Deductions:
${deductions || "  (none)"}

━━━━━━━━━━━━━━━━
Net Profit:       $${Number(settlement.profit).toFixed(2)}
Status:           ${settlement.status.toUpperCase()}

${settlement.status === "paid" ? "✅ Payout has been processed via Stripe." : "⏳ Payout pending approval."}

This report was generated by Nocturn.
View full details: ${process.env.NEXT_PUBLIC_APP_URL || "https://app.trynocturn.com"}/dashboard/finance/${settlement.event_id}

— Nocturn`;

  // Actually send the email via Resend singleton if configured
  let sent = false;
  const resend = getResendClient();
  if (resend && recipientEmails.length > 0) {
    try {
      await resend.emails.send({
        from: "Nocturn <noreply@trynocturn.com>",
        to: recipientEmails,
        subject,
        text: body,
      });
      sent = true;
    } catch (emailError) {
      console.error("[settlement-email] Failed to send:", emailError);
      // Non-blocking — return the report even if email fails
    }
  }

  return {
    error: null,
    report: {
      subject,
      body,
      recipients: recipientEmails,
      sent,
    },
  };
}
