"use server";

import { createClient as createServerClient } from "@/lib/supabase/server";
import { createAdminClient } from "@/lib/supabase/config";
import { getResendClient } from "@/lib/resend";

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

// Generate a settlement report email and return it (for now, no Resend — just generates the content)
export async function generateSettlementReport(settlementId: string) {
  const supabase = await createServerClient();
  const { data: { user } } = await supabase.auth.getUser();
  if (!user) return { error: "Not authenticated", report: null };

  const admin = createAdminClient();

  // Get settlement with event and collective
  const { data: settlement } = await admin
    .from("settlements")
    .select("*, events(title, starts_at, venues(name, city)), collectives(name)")
    .eq("id", settlementId)
    .maybeSingle();

  if (!settlement) return { error: "Settlement not found", report: null };

  // Verify user is an admin or promoter of this collective
  const { data: membership } = await admin
    .from("collective_members")
    .select("role")
    .eq("collective_id", settlement.collective_id)
    .eq("user_id", user.id)
    .in("role", ["admin", "promoter"])
    .is("deleted_at", null)
    .maybeSingle();
  if (!membership) return { error: "Not authorized", report: null };

  // Get line items
  const { data: lines } = await admin
    .from("settlement_lines")
    .select("*")
    .eq("settlement_id", settlementId)
    .order("created_at");

  // Get collective members for emailing
  const { data: members } = await admin
    .from("collective_members")
    .select("users(full_name, email)")
    .eq("collective_id", settlement.collective_id)
    .is("deleted_at", null);

  const event = settlement.events as unknown as {
    title: string;
    starts_at: string;
    venues: { name: string; city: string } | null;
  } | null;
  const collective = settlement.collectives as unknown as { name: string } | null;

  if (!event) {
    return { error: "Event associated with this settlement no longer exists", report: null };
  }

  const venue = event.venues;
  const eventDate = new Date(event.starts_at).toLocaleDateString("en", {
    weekday: "long",
    month: "long",
    day: "numeric",
    year: "numeric",
  });

  const recipientEmails = (members ?? [])
    .map((m) => {
      const u = m.users as unknown as { full_name: string; email: string } | null;
      return u?.email;
    })
    .filter(Boolean) as string[];

  // Build report
  const deductions = (lines ?? [])
    .map((l) => `  • ${l.label}: -$${Number(l.amount).toFixed(2)}`)
    .join("\n");

  const collectiveName = escapeHtml(collective?.name ?? "Your Collective");
  const safeEventTitle = escapeHtml(event.title);
  const safeVenueName = venue ? escapeHtml(venue.name) : null;
  const subject = `Settlement Report: ${safeEventTitle} — ${collectiveName}`;

  const body = `Hi ${collectiveName} team,

Here's the settlement report for ${safeEventTitle}.

EVENT DETAILS
━━━━━━━━━━━━
Event: ${safeEventTitle}
Date: ${eventDate}
Venue: ${safeVenueName ? `${safeVenueName}, ${venue!.city}` : "N/A"}

FINANCIAL SUMMARY
━━━━━━━━━━━━━━━━
Gross Revenue:    $${Number(settlement.gross_revenue).toFixed(2)}

Deductions:
${deductions || "  (none)"}

━━━━━━━━━━━━━━━━
Net Profit:       $${Number(settlement.profit ?? 0).toFixed(2)}
Status:           ${(settlement.status ?? "pending").toUpperCase()}

${settlement.status === "paid" ? "✅ Payout has been processed via Stripe." : "⏳ Payout pending approval."}

This report was generated by Nocturn.
View full details: ${process.env.NEXT_PUBLIC_APP_URL || "https://app.trynocturn.com"}/dashboard/finance/${settlement.event_id}

— Nocturn`;

  // Actually send the email via Resend singleton if configured
  let sent = false;
  const resend = getResendClient();
  if (resend && recipientEmails.length > 0) {
    try {
      await resend.emails.send({
        from: "Nocturn <noreply@trynocturn.com>",
        to: recipientEmails,
        subject,
        text: body,
      });
      sent = true;
    } catch (emailError) {
      console.error("[settlement-email] Failed to send:", emailError);
      // Non-blocking — return the report even if email fails
    }
  }

  return {
    error: null,
    report: {
      subject,
      body,
      recipients: recipientEmails,
      sent,
    },
  };
}
